### ISSUE TITLE
大哥你好

### ISSUE THREAD

**Issue by c3poo** [r00tSe7en/Flash-Pop#2]
js是不是有些bug，还是flash最近更新了网页？好像拉不起来flash

**Comment by r00tSe7en** [comment]
这个要自己手动替换下里面的js地址，我的子域已经停止解析了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "r00tSe7en/Flash-Pop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[r00tSe7en/Flash-Pop] 大哥你好 (Issue #2)





 
js是不是有些bug，还是flash最近更新了网页？好像拉不起来flash
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by c3poo** [comment]
本地的js方便发一下吗，我放根目录就不用解析啦，谢谢大佬😂






2021年11月22日 星期一 +0800 16:58 寄件人 ***@***.***  ***@***.***>:

**Comment by c3poo** [comment]
已解决 谢谢大哥
